<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $title ?? 'Partner Portal' }} - ResellNom</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;background:#f6f8fc;color:#172033}
.shell{display:flex;min-height:100vh}.side{width:245px;background:#101827;color:#dce5f3;padding:22px 14px;position:fixed;inset:0 auto 0 0}.brand{font-size:19px;font-weight:800;padding:8px 12px 28px;color:#fff}.brand span{color:#35a7ff;font-size:11px;display:block;margin-top:2px}.nav a{display:flex;gap:12px;padding:11px 13px;margin:3px 0;border-radius:9px;color:#aebbd0;text-decoration:none;font-size:14px}.nav a.active,.nav a:hover{background:#1677e8;color:#fff}.main{margin-left:245px;flex:1}.top{height:68px;background:#fff;border-bottom:1px solid #e7ebf2;display:flex;align-items:center;justify-content:space-between;padding:0 30px}.select{border:1px solid #e3e8f0;padding:9px 13px;border-radius:9px;background:#fff}.user{display:flex;gap:10px;align-items:center;font-size:14px}.avatar{width:34px;height:34px;border-radius:50%;background:#1479e9;color:#fff;display:grid;place-items:center;font-weight:700}.content{padding:30px;max-width:1400px}.muted{color:#758198}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:24px 0}.card{background:#fff;border:1px solid #e6ebf2;border-radius:13px;padding:20px;box-shadow:0 2px 8px #17203308}.label{font-size:13px;color:#748097}.value{font-size:25px;font-weight:800;margin:7px 0}.up{color:#16a36b;font-size:12px}.grid2{display:grid;grid-template-columns:1.6fr 1fr;gap:18px}.panel{background:#fff;border:1px solid #e6ebf2;border-radius:13px;padding:20px}.panel h3{margin:0 0 18px}.chart{height:220px;display:flex;align-items:end;gap:12px;padding:15px 5px}.bar{flex:1;background:#d8eaff;border-radius:6px 6px 0 0}.bar:nth-child(1){height:42%}.bar:nth-child(2){height:55%}.bar:nth-child(3){height:48%}.bar:nth-child(4){height:72%}.bar:nth-child(5){height:61%}.bar:nth-child(6){height:82%}.bar:nth-child(7){height:76%}.bar:nth-child(8){height:94%}.bar:nth-child(9){height:88%}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:12px 8px;border-bottom:1px solid #edf0f5;font-size:13px}.badge{padding:4px 8px;border-radius:20px;font-size:11px}.paid{background:#e7f8f0;color:#13875a}.pending{background:#fff4d8;color:#a16b00}.open{background:#ffe8e8;color:#c33}.btn{border:0;border-radius:8px;padding:9px 13px;background:#1479e9;color:#fff;font-weight:700}.quick{display:grid;gap:9px}.quick .btn{width:100%;text-align:left}.mobile{display:none}
@media(max-width:900px){.side{display:none}.main{margin-left:0}.mobile{display:block}.top{padding:0 16px}.content{padding:18px}.cards{grid-template-columns:repeat(2,1fr)}.grid2{grid-template-columns:1fr}}
@media(max-width:520px){.cards{grid-template-columns:1fr}.top .select{display:none}.table{min-width:650px}.panel{overflow:auto}}
</style>
</head>
<body>
<div class="shell"><aside class="side"><div class="brand">◉ ResellNom<span>PARTNER PLATFORM</span></div><nav class="nav">
<a href="{{ route('partner.dashboard') }}">▣ Dashboard</a><a href="{{ route('partner.products') }}">▦ Products</a><a href="#">▤ Orders</a><a href="#">♙ Customers</a><a href="#">◈ Services</a><a href="#">◉ Commissions</a><a href="{{ route('partner.withdraw') }}">৳ Withdraw</a><a href="{{ route('partner.support') }}">✉ Support Tickets</a><a href="#">◫ My Store</a><a href="{{ route('partner.domain-branding') }}">◎ Domain & Branding</a><a href="#">▥ Reports</a><a href="#">⚙ Settings</a>
</nav></aside><main class="main"><header class="top"><div class="mobile">☰</div><select class="select"><option>ABC Hosting</option></select><div class="user"><span>🔔</span><span>Mahfuz<br><small class="muted">Partner</small></span><div class="avatar">M</div></div></header><section class="content">@yield('content')</section></main></div>
</body></html>